using UnityEngine;

public class MouseInput : MonoBehaviour
{

    [Header("Input Settings:")]
     float pressureForce;

    protected RaycastHit hitInfo;
    protected Ray ray;

    protected Vector3 inputPoint;
    protected JellyBody jellyBody;
    protected GameObject[] SphereBox = new GameObject[800];
    // protected GameObject jelly;
    float k = 0;


    public static MouseInput instance;

    private void Start()
    {
        instance = this;
        //jelly = GameObject.FindGameObjectWithTag("Player");
        SphereBox[0] = GameObject.Find("Sphere");
        SphereBox[1] = GameObject.Find("Sphere (1)");
        SphereBox[2] = GameObject.Find("Sphere (2)");
        SphereBox[3] = GameObject.Find("Sphere (3)");
        SphereBox[4] = GameObject.Find("Sphere (4)");
        SphereBox[5] = GameObject.Find("Sphere (5)");
        SphereBox[6] = GameObject.Find("Sphere (6)");
        SphereBox[7] = GameObject.Find("Sphere (7)");
        SphereBox[8] = GameObject.Find("Sphere (8)");
        SphereBox[9] = GameObject.Find("Sphere (9)");
        SphereBox[10] = GameObject.Find("Sphere (10)");
        SphereBox[11] = GameObject.Find("Sphere (11)");
        SphereBox[12] = GameObject.Find("Sphere (12)");
        SphereBox[13] = GameObject.Find("Sphere (13)");
        SphereBox[14] = GameObject.Find("Sphere (14)");
        SphereBox[15] = GameObject.Find("Sphere (15)");
        SphereBox[16] = GameObject.Find("Sphere (16)");
        SphereBox[17] = GameObject.Find("Sphere (17)");
        SphereBox[18] = GameObject.Find("Sphere (18)");
        SphereBox[19] = GameObject.Find("Sphere (19)");
        SphereBox[20] = GameObject.Find("Sphere (20)");
        SphereBox[21] = GameObject.Find("Sphere (21)");
        SphereBox[22] = GameObject.Find("Sphere (22)");
        SphereBox[23] = GameObject.Find("Sphere (23)");
        SphereBox[24] = GameObject.Find("Sphere (24)");
        SphereBox[25] = GameObject.Find("Sphere (25)");
        SphereBox[26] = GameObject.Find("Sphere (26)");
        SphereBox[27] = GameObject.Find("Sphere (27)");
        SphereBox[28] = GameObject.Find("Sphere (28)");
        SphereBox[29] = GameObject.Find("Sphere (29)");
        SphereBox[30] = GameObject.Find("Sphere (30)");
        SphereBox[31] = GameObject.Find("Sphere (31)");
        SphereBox[32] = GameObject.Find("Sphere (32)");
        SphereBox[33] = GameObject.Find("Sphere (33)");
        SphereBox[34] = GameObject.Find("Sphere (34)");
        SphereBox[35] = GameObject.Find("Sphere (35)");
        SphereBox[36] = GameObject.Find("Sphere (36)");
        SphereBox[37] = GameObject.Find("Sphere (37)");
        SphereBox[38] = GameObject.Find("Sphere (38)");
        SphereBox[39] = GameObject.Find("Sphere (39)");
        SphereBox[40] = GameObject.Find("Sphere (40)");
        SphereBox[41] = GameObject.Find("Sphere (41)");
        SphereBox[42] = GameObject.Find("Sphere (42)");
        SphereBox[43] = GameObject.Find("Sphere (43)");
        SphereBox[44] = GameObject.Find("Sphere (44)");
        SphereBox[45] = GameObject.Find("Sphere (45)");
        SphereBox[46] = GameObject.Find("Sphere (46)");
        SphereBox[47] = GameObject.Find("Sphere (47)");
        SphereBox[48] = GameObject.Find("Sphere (48)");
        SphereBox[49] = GameObject.Find("Sphere (49)");
        SphereBox[50] = GameObject.Find("Sphere (50)");
        SphereBox[51] = GameObject.Find("Sphere (51)");
        SphereBox[52] = GameObject.Find("Sphere (52)");
        SphereBox[53] = GameObject.Find("Sphere (53)");
        SphereBox[54] = GameObject.Find("Sphere (54)");
        SphereBox[55] = GameObject.Find("Sphere (55)");
        SphereBox[56] = GameObject.Find("Sphere (56)");
        SphereBox[57] = GameObject.Find("Sphere (57)");
        SphereBox[58] = GameObject.Find("Sphere (58)");
        SphereBox[59] = GameObject.Find("Sphere (59)");
        SphereBox[60] = GameObject.Find("Sphere (60)");
        SphereBox[61] = GameObject.Find("Sphere (61)");
        SphereBox[62] = GameObject.Find("Sphere (62)");
        SphereBox[63] = GameObject.Find("Sphere (63)");
        SphereBox[64] = GameObject.Find("Sphere (64)");
        SphereBox[65] = GameObject.Find("Sphere (65)");
        SphereBox[66] = GameObject.Find("Sphere (66)");
        SphereBox[67] = GameObject.Find("Sphere (67)");
        SphereBox[68] = GameObject.Find("Sphere (68)");
        SphereBox[69] = GameObject.Find("Sphere (69)");
        SphereBox[70] = GameObject.Find("Sphere (70)");
        SphereBox[71] = GameObject.Find("Sphere (71)");
        SphereBox[72] = GameObject.Find("Sphere (72)");
        SphereBox[73] = GameObject.Find("Sphere (73)");
        SphereBox[74] = GameObject.Find("Sphere (74)");
        SphereBox[75] = GameObject.Find("Sphere (75)");
        SphereBox[76] = GameObject.Find("Sphere (76)");
        SphereBox[77] = GameObject.Find("Sphere (77)");
        SphereBox[78] = GameObject.Find("Sphere (78)");
        SphereBox[79] = GameObject.Find("Sphere (79)");
        SphereBox[80] = GameObject.Find("Sphere (80)");
        SphereBox[81] = GameObject.Find("Sphere (81)");
        SphereBox[82] = GameObject.Find("Sphere (82)");
        SphereBox[83] = GameObject.Find("Sphere (83)");
        SphereBox[84] = GameObject.Find("Sphere (84)");
        SphereBox[85] = GameObject.Find("Sphere (85)");
        SphereBox[86] = GameObject.Find("Sphere (86)");
        SphereBox[87] = GameObject.Find("Sphere (87)");
        SphereBox[88] = GameObject.Find("Sphere (88)");
        SphereBox[89] = GameObject.Find("Sphere (89)");
        SphereBox[90] = GameObject.Find("Sphere (90)");
        SphereBox[91] = GameObject.Find("Sphere (91)");
        SphereBox[92] = GameObject.Find("Sphere (92)");
        SphereBox[93] = GameObject.Find("Sphere (93)");
        SphereBox[94] = GameObject.Find("Sphere (94)");
        SphereBox[95] = GameObject.Find("Sphere (95)");
        SphereBox[96] = GameObject.Find("Sphere (96)");
        SphereBox[97] = GameObject.Find("Sphere (97)");
        SphereBox[98] = GameObject.Find("Sphere (98)");
        SphereBox[99] = GameObject.Find("Sphere (99)");
        SphereBox[100] = GameObject.Find("Sphere (100)");
        SphereBox[101] = GameObject.Find("Sphere (101)");
        SphereBox[102] = GameObject.Find("Sphere (102)");
        SphereBox[103] = GameObject.Find("Sphere (103)");
        SphereBox[104] = GameObject.Find("Sphere (104)");
        SphereBox[105] = GameObject.Find("Sphere (105)");
        SphereBox[106] = GameObject.Find("Sphere (106)");
        SphereBox[107] = GameObject.Find("Sphere (107)");
        SphereBox[108] = GameObject.Find("Sphere (108)");
        SphereBox[109] = GameObject.Find("Sphere (109)");
        SphereBox[110] = GameObject.Find("Sphere (110)");
        SphereBox[111] = GameObject.Find("Sphere (111)");
        SphereBox[112] = GameObject.Find("Sphere (112)");
        SphereBox[113] = GameObject.Find("Sphere (113)");
        SphereBox[114] = GameObject.Find("Sphere (114)");
        SphereBox[115] = GameObject.Find("Sphere (115)");
        SphereBox[116] = GameObject.Find("Sphere (116)");
        SphereBox[117] = GameObject.Find("Sphere (117)");
        SphereBox[118] = GameObject.Find("Sphere (118)");
        SphereBox[119] = GameObject.Find("Sphere (119)");
        SphereBox[120] = GameObject.Find("Sphere (120)");
        SphereBox[121] = GameObject.Find("Sphere (121)");
        SphereBox[122] = GameObject.Find("Sphere (122)");
        SphereBox[123] = GameObject.Find("Sphere (123)");
        SphereBox[124] = GameObject.Find("Sphere (124)");
        SphereBox[125] = GameObject.Find("Sphere (125)");
        SphereBox[126] = GameObject.Find("Sphere (126)");
        SphereBox[127] = GameObject.Find("Sphere (127)");
        SphereBox[128] = GameObject.Find("Sphere (128)");
        SphereBox[129] = GameObject.Find("Sphere (129)");
        SphereBox[130] = GameObject.Find("Sphere (130)");
        SphereBox[131] = GameObject.Find("Sphere (131)");
        SphereBox[132] = GameObject.Find("Sphere (132)");
        SphereBox[133] = GameObject.Find("Sphere (133)");
        SphereBox[134] = GameObject.Find("Sphere (134)");
        SphereBox[135] = GameObject.Find("Sphere (135)");
        SphereBox[136] = GameObject.Find("Sphere (136)");
        SphereBox[137] = GameObject.Find("Sphere (137)");
        SphereBox[138] = GameObject.Find("Sphere (138)");
        SphereBox[139] = GameObject.Find("Sphere (139)");
        SphereBox[140] = GameObject.Find("Sphere (140)");
        SphereBox[141] = GameObject.Find("Sphere (141)");
        SphereBox[142] = GameObject.Find("Sphere (142)");
        SphereBox[143] = GameObject.Find("Sphere (143)");
        SphereBox[144] = GameObject.Find("Sphere (144)");
        SphereBox[145] = GameObject.Find("Sphere (145)");
        SphereBox[146] = GameObject.Find("Sphere (146)");
        SphereBox[147] = GameObject.Find("Sphere (147)");
        SphereBox[148] = GameObject.Find("Sphere (148)");
        SphereBox[149] = GameObject.Find("Sphere (149)");
        SphereBox[150] = GameObject.Find("Sphere (150)");
        SphereBox[151] = GameObject.Find("Sphere (151)");
        SphereBox[152] = GameObject.Find("Sphere (152)");
        SphereBox[153] = GameObject.Find("Sphere (153)");
        SphereBox[154] = GameObject.Find("Sphere (154)");
        SphereBox[155] = GameObject.Find("Sphere (155)");
        SphereBox[156] = GameObject.Find("Sphere (156)");
        SphereBox[157] = GameObject.Find("Sphere (157)");
        SphereBox[158] = GameObject.Find("Sphere (158)");
        SphereBox[159] = GameObject.Find("Sphere (159)");
        SphereBox[160] = GameObject.Find("Sphere (160)");
        SphereBox[161] = GameObject.Find("Sphere (161)");
        SphereBox[162] = GameObject.Find("Sphere (162)");
        SphereBox[163] = GameObject.Find("Sphere (163)");
        SphereBox[164] = GameObject.Find("Sphere (164)");
        SphereBox[165] = GameObject.Find("Sphere (165)");
        SphereBox[166] = GameObject.Find("Sphere (166)");
        SphereBox[167] = GameObject.Find("Sphere (167)");
        SphereBox[168] = GameObject.Find("Sphere (168)");
        SphereBox[169] = GameObject.Find("Sphere (169)");
        SphereBox[170] = GameObject.Find("Sphere (170)");
        SphereBox[171] = GameObject.Find("Sphere (171)");
        SphereBox[172] = GameObject.Find("Sphere (172)");
        SphereBox[173] = GameObject.Find("Sphere (173)");
        SphereBox[174] = GameObject.Find("Sphere (174)");
        SphereBox[175] = GameObject.Find("Sphere (175)");
        SphereBox[176] = GameObject.Find("Sphere (176)");
        SphereBox[177] = GameObject.Find("Sphere (177)");
        SphereBox[178] = GameObject.Find("Sphere (178)");
        SphereBox[179] = GameObject.Find("Sphere (179)");
        SphereBox[180] = GameObject.Find("Sphere (180)");
        SphereBox[181] = GameObject.Find("Sphere (181)");
        SphereBox[182] = GameObject.Find("Sphere (182)");
        SphereBox[183] = GameObject.Find("Sphere (183)");
        SphereBox[184] = GameObject.Find("Sphere (184)");
        SphereBox[185] = GameObject.Find("Sphere (185)");
        SphereBox[186] = GameObject.Find("Sphere (186)");
        SphereBox[187] = GameObject.Find("Sphere (187)");
        SphereBox[188] = GameObject.Find("Sphere (188)");
        SphereBox[189] = GameObject.Find("Sphere (189)");
        SphereBox[190] = GameObject.Find("Sphere (190)");
        SphereBox[191] = GameObject.Find("Sphere (191)");
        SphereBox[192] = GameObject.Find("Sphere (192)");
        SphereBox[193] = GameObject.Find("Sphere (193)");
        SphereBox[194] = GameObject.Find("Sphere (194)");
        SphereBox[195] = GameObject.Find("Sphere (195)");
        SphereBox[196] = GameObject.Find("Sphere (196)");
        SphereBox[197] = GameObject.Find("Sphere (197)");
        SphereBox[198] = GameObject.Find("Sphere (198)");
        SphereBox[199] = GameObject.Find("Sphere (199)");
        SphereBox[200] = GameObject.Find("Sphere (200)");
        SphereBox[201] = GameObject.Find("Sphere (201)");
        SphereBox[202] = GameObject.Find("Sphere (202)");
        SphereBox[203] = GameObject.Find("Sphere (203)");
        SphereBox[204] = GameObject.Find("Sphere (204)");
        SphereBox[205] = GameObject.Find("Sphere (205)");
        SphereBox[206] = GameObject.Find("Sphere (206)");
        SphereBox[207] = GameObject.Find("Sphere (207)");
        SphereBox[208] = GameObject.Find("Sphere (208)");
        SphereBox[209] = GameObject.Find("Sphere (209)");
        SphereBox[210] = GameObject.Find("Sphere (210)");
        SphereBox[211] = GameObject.Find("Sphere (211)");
        SphereBox[212] = GameObject.Find("Sphere (212)");
        SphereBox[213] = GameObject.Find("Sphere (213)");
        SphereBox[214] = GameObject.Find("Sphere (214)");
        SphereBox[215] = GameObject.Find("Sphere (215)");
        SphereBox[216] = GameObject.Find("Sphere (216)");
        SphereBox[217] = GameObject.Find("Sphere (217)");
        SphereBox[218] = GameObject.Find("Sphere (218)");
        SphereBox[219] = GameObject.Find("Sphere (219)");
        SphereBox[220] = GameObject.Find("Sphere (220)");
        SphereBox[221] = GameObject.Find("Sphere (221)");
        SphereBox[222] = GameObject.Find("Sphere (222)");
        SphereBox[223] = GameObject.Find("Sphere (223)");
        SphereBox[224] = GameObject.Find("Sphere (224)");
        SphereBox[225] = GameObject.Find("Sphere (225)");
        SphereBox[226] = GameObject.Find("Sphere (226)");
        SphereBox[227] = GameObject.Find("Sphere (227)");
        SphereBox[228] = GameObject.Find("Sphere (228)");
        SphereBox[229] = GameObject.Find("Sphere (229)");
        SphereBox[230] = GameObject.Find("Sphere (230)");
        SphereBox[231] = GameObject.Find("Sphere (231)");
        SphereBox[232] = GameObject.Find("Sphere (232)");
        SphereBox[233] = GameObject.Find("Sphere (233)");
        SphereBox[234] = GameObject.Find("Sphere (234)");
        SphereBox[235] = GameObject.Find("Sphere (235)");
        SphereBox[236] = GameObject.Find("Sphere (236)");
        SphereBox[237] = GameObject.Find("Sphere (237)");
        SphereBox[238] = GameObject.Find("Sphere (238)");
        SphereBox[239] = GameObject.Find("Sphere (239)");
        SphereBox[240] = GameObject.Find("Sphere (240)");
        SphereBox[241] = GameObject.Find("Sphere (241)");
        SphereBox[242] = GameObject.Find("Sphere (242)");
        SphereBox[243] = GameObject.Find("Sphere (243)");
        SphereBox[244] = GameObject.Find("Sphere (244)");
        SphereBox[245] = GameObject.Find("Sphere (245)");
        SphereBox[246] = GameObject.Find("Sphere (246)");
        SphereBox[247] = GameObject.Find("Sphere (247)");
        SphereBox[248] = GameObject.Find("Sphere (248)");
        SphereBox[249] = GameObject.Find("Sphere (249)");
        SphereBox[250] = GameObject.Find("Sphere (250)");
        SphereBox[251] = GameObject.Find("Sphere (251)");
        SphereBox[252] = GameObject.Find("Sphere (252)");
        SphereBox[253] = GameObject.Find("Sphere (253)");
        SphereBox[254] = GameObject.Find("Sphere (254)");
        SphereBox[255] = GameObject.Find("Sphere (255)");
        SphereBox[256] = GameObject.Find("Sphere (256)");
        SphereBox[257] = GameObject.Find("Sphere (257)");
        SphereBox[258] = GameObject.Find("Sphere (258)");
        SphereBox[259] = GameObject.Find("Sphere (259)");
        SphereBox[260] = GameObject.Find("Sphere (260)");
        SphereBox[261] = GameObject.Find("Sphere (261)");
        SphereBox[262] = GameObject.Find("Sphere (262)");
        SphereBox[263] = GameObject.Find("Sphere (263)");
        SphereBox[264] = GameObject.Find("Sphere (264)");
        SphereBox[265] = GameObject.Find("Sphere (265)");
        SphereBox[266] = GameObject.Find("Sphere (266)");
        SphereBox[267] = GameObject.Find("Sphere (267)");
        SphereBox[268] = GameObject.Find("Sphere (268)");
        SphereBox[269] = GameObject.Find("Sphere (269)");
        SphereBox[270] = GameObject.Find("Sphere (270)");
        SphereBox[271] = GameObject.Find("Sphere (271)");
        SphereBox[272] = GameObject.Find("Sphere (272)");
        SphereBox[273] = GameObject.Find("Sphere (273)");
        SphereBox[274] = GameObject.Find("Sphere (274)");
        SphereBox[275] = GameObject.Find("Sphere (275)");
        SphereBox[276] = GameObject.Find("Sphere (276)");
        SphereBox[277] = GameObject.Find("Sphere (277)");
        SphereBox[278] = GameObject.Find("Sphere (278)");
        SphereBox[279] = GameObject.Find("Sphere (279)");
        SphereBox[280] = GameObject.Find("Sphere (280)");
        SphereBox[281] = GameObject.Find("Sphere (281)");
        SphereBox[282] = GameObject.Find("Sphere (282)");
        SphereBox[283] = GameObject.Find("Sphere (283)");
        SphereBox[284] = GameObject.Find("Sphere (284)");
        SphereBox[285] = GameObject.Find("Sphere (285)");
        SphereBox[286] = GameObject.Find("Sphere (286)");
        SphereBox[287] = GameObject.Find("Sphere (287)");
        SphereBox[288] = GameObject.Find("Sphere (288)");
        SphereBox[289] = GameObject.Find("Sphere (289)");
        SphereBox[290] = GameObject.Find("Sphere (290)");
        SphereBox[291] = GameObject.Find("Sphere (291)");
        SphereBox[292] = GameObject.Find("Sphere (292)");
        SphereBox[293] = GameObject.Find("Sphere (293)");
        SphereBox[294] = GameObject.Find("Sphere (294)");
        SphereBox[295] = GameObject.Find("Sphere (295)");
        SphereBox[296] = GameObject.Find("Sphere (296)");
        SphereBox[297] = GameObject.Find("Sphere (297)");
        SphereBox[298] = GameObject.Find("Sphere (298)");
        SphereBox[299] = GameObject.Find("Sphere (299)");
        SphereBox[300] = GameObject.Find("Sphere (300)");
        SphereBox[301] = GameObject.Find("Sphere (301)");
        SphereBox[302] = GameObject.Find("Sphere (302)");
        SphereBox[303] = GameObject.Find("Sphere (303)");
        SphereBox[304] = GameObject.Find("Sphere (304)");
        SphereBox[305] = GameObject.Find("Sphere (305)");
        SphereBox[306] = GameObject.Find("Sphere (306)");
        SphereBox[307] = GameObject.Find("Sphere (307)");
        SphereBox[308] = GameObject.Find("Sphere (308)");
        SphereBox[309] = GameObject.Find("Sphere (309)");
        SphereBox[310] = GameObject.Find("Sphere (310)");
        SphereBox[311] = GameObject.Find("Sphere (311)");
        SphereBox[312] = GameObject.Find("Sphere (312)");
        SphereBox[313] = GameObject.Find("Sphere (313)");
        SphereBox[314] = GameObject.Find("Sphere (314)");
        SphereBox[315] = GameObject.Find("Sphere (315)");
        SphereBox[316] = GameObject.Find("Sphere (316)");
        SphereBox[317] = GameObject.Find("Sphere (317)");
        SphereBox[318] = GameObject.Find("Sphere (318)");
        SphereBox[319] = GameObject.Find("Sphere (319)");
        SphereBox[320] = GameObject.Find("Sphere (320)");
        SphereBox[321] = GameObject.Find("Sphere (321)");
        SphereBox[322] = GameObject.Find("Sphere (322)");
        SphereBox[323] = GameObject.Find("Sphere (323)");
        SphereBox[324] = GameObject.Find("Sphere (324)");
        SphereBox[325] = GameObject.Find("Sphere (325)");
        SphereBox[326] = GameObject.Find("Sphere (326)");
        SphereBox[327] = GameObject.Find("Sphere (327)");
        SphereBox[328] = GameObject.Find("Sphere (328)");
        SphereBox[329] = GameObject.Find("Sphere (329)");
        SphereBox[330] = GameObject.Find("Sphere (330)");
        SphereBox[331] = GameObject.Find("Sphere (331)");
        SphereBox[332] = GameObject.Find("Sphere (332)");
        SphereBox[333] = GameObject.Find("Sphere (333)");
        SphereBox[334] = GameObject.Find("Sphere (334)");
        SphereBox[335] = GameObject.Find("Sphere (335)");
        SphereBox[336] = GameObject.Find("Sphere (336)");
        SphereBox[337] = GameObject.Find("Sphere (337)");
        SphereBox[338] = GameObject.Find("Sphere (338)");
        SphereBox[339] = GameObject.Find("Sphere (339)");
        SphereBox[340] = GameObject.Find("Sphere (340)");
        SphereBox[341] = GameObject.Find("Sphere (341)");
        SphereBox[342] = GameObject.Find("Sphere (342)");
        SphereBox[343] = GameObject.Find("Sphere (343)");
        SphereBox[344] = GameObject.Find("Sphere (344)");
        SphereBox[345] = GameObject.Find("Sphere (345)");
        SphereBox[346] = GameObject.Find("Sphere (346)");
        SphereBox[347] = GameObject.Find("Sphere (347)");
        SphereBox[348] = GameObject.Find("Sphere (348)");
        SphereBox[349] = GameObject.Find("Sphere (349)");
        SphereBox[350] = GameObject.Find("Sphere (350)");
        SphereBox[351] = GameObject.Find("Sphere (351)");
        SphereBox[352] = GameObject.Find("Sphere (352)");
        SphereBox[353] = GameObject.Find("Sphere (353)");
        SphereBox[354] = GameObject.Find("Sphere (354)");
        SphereBox[355] = GameObject.Find("Sphere (355)");
        SphereBox[356] = GameObject.Find("Sphere (356)");
        SphereBox[357] = GameObject.Find("Sphere (357)");
        SphereBox[358] = GameObject.Find("Sphere (358)");
        SphereBox[359] = GameObject.Find("Sphere (359)");
        SphereBox[360] = GameObject.Find("Sphere (360)");
        SphereBox[361] = GameObject.Find("Sphere (361)");
        SphereBox[362] = GameObject.Find("Sphere (362)");
        SphereBox[363] = GameObject.Find("Sphere (363)");
        SphereBox[364] = GameObject.Find("Sphere (364)");
        SphereBox[365] = GameObject.Find("Sphere (365)");
        SphereBox[366] = GameObject.Find("Sphere (366)");
        SphereBox[367] = GameObject.Find("Sphere (367)");
        SphereBox[368] = GameObject.Find("Sphere (368)");
        SphereBox[369] = GameObject.Find("Sphere (369)");
        SphereBox[370] = GameObject.Find("Sphere (370)");
        SphereBox[371] = GameObject.Find("Sphere (371)");
        SphereBox[372] = GameObject.Find("Sphere (372)");
        SphereBox[373] = GameObject.Find("Sphere (373)");
        SphereBox[374] = GameObject.Find("Sphere (374)");
        SphereBox[375] = GameObject.Find("Sphere (375)");
        SphereBox[376] = GameObject.Find("Sphere (376)");
        SphereBox[377] = GameObject.Find("Sphere (377)");
        SphereBox[378] = GameObject.Find("Sphere (378)");
        SphereBox[379] = GameObject.Find("Sphere (379)");
        SphereBox[380] = GameObject.Find("Sphere (380)");
        SphereBox[381] = GameObject.Find("Sphere (381)");
        SphereBox[382] = GameObject.Find("Sphere (382)");
        SphereBox[383] = GameObject.Find("Sphere (383)");
        SphereBox[384] = GameObject.Find("Sphere (384)");
        SphereBox[385] = GameObject.Find("Sphere (385)");
        SphereBox[386] = GameObject.Find("Sphere (386)");
        SphereBox[387] = GameObject.Find("Sphere (387)");
        SphereBox[388] = GameObject.Find("Sphere (388)");
        SphereBox[389] = GameObject.Find("Sphere (389)");
        SphereBox[390] = GameObject.Find("Sphere (390)");
        SphereBox[391] = GameObject.Find("Sphere (391)");
        SphereBox[392] = GameObject.Find("Sphere (392)");
        SphereBox[393] = GameObject.Find("Sphere (393)");
        SphereBox[394] = GameObject.Find("Sphere (394)");
        SphereBox[395] = GameObject.Find("Sphere (395)");
        SphereBox[396] = GameObject.Find("Sphere (396)");
        SphereBox[397] = GameObject.Find("Sphere (397)");
        SphereBox[398] = GameObject.Find("Sphere (398)");
        SphereBox[399] = GameObject.Find("Sphere (399)");
        SphereBox[400] = GameObject.Find("Sphere (400)");
        SphereBox[401] = GameObject.Find("Sphere (401)");
        SphereBox[402] = GameObject.Find("Sphere (402)");
        SphereBox[403] = GameObject.Find("Sphere (403)");
        SphereBox[404] = GameObject.Find("Sphere (404)");
        SphereBox[405] = GameObject.Find("Sphere (405)");
        SphereBox[406] = GameObject.Find("Sphere (406)");
        SphereBox[407] = GameObject.Find("Sphere (407)");
        SphereBox[408] = GameObject.Find("Sphere (408)");
        SphereBox[409] = GameObject.Find("Sphere (409)");
        SphereBox[410] = GameObject.Find("Sphere (410)");
        SphereBox[411] = GameObject.Find("Sphere (411)");
        SphereBox[412] = GameObject.Find("Sphere (412)");
        SphereBox[413] = GameObject.Find("Sphere (413)");
        SphereBox[414] = GameObject.Find("Sphere (414)");
        SphereBox[415] = GameObject.Find("Sphere (415)");
        SphereBox[416] = GameObject.Find("Sphere (416)");
        SphereBox[417] = GameObject.Find("Sphere (417)");
        SphereBox[418] = GameObject.Find("Sphere (418)");
        SphereBox[419] = GameObject.Find("Sphere (419)");
        SphereBox[420] = GameObject.Find("Sphere (420)");
        SphereBox[421] = GameObject.Find("Sphere (421)");
        SphereBox[422] = GameObject.Find("Sphere (422)");
        SphereBox[423] = GameObject.Find("Sphere (423)");
        SphereBox[424] = GameObject.Find("Sphere (424)");
        SphereBox[425] = GameObject.Find("Sphere (425)");
        SphereBox[426] = GameObject.Find("Sphere (426)");
        SphereBox[427] = GameObject.Find("Sphere (427)");
        SphereBox[428] = GameObject.Find("Sphere (428)");
        SphereBox[429] = GameObject.Find("Sphere (429)");
        SphereBox[430] = GameObject.Find("Sphere (430)");
        SphereBox[431] = GameObject.Find("Sphere (431)");
        SphereBox[432] = GameObject.Find("Sphere (432)");
        SphereBox[433] = GameObject.Find("Sphere (433)");
        SphereBox[434] = GameObject.Find("Sphere (434)");
        SphereBox[435] = GameObject.Find("Sphere (435)");
        SphereBox[436] = GameObject.Find("Sphere (436)");
        SphereBox[437] = GameObject.Find("Sphere (437)");
        SphereBox[438] = GameObject.Find("Sphere (438)");
        SphereBox[439] = GameObject.Find("Sphere (439)");
        SphereBox[440] = GameObject.Find("Sphere (440)");
        SphereBox[441] = GameObject.Find("Sphere (441)");
        SphereBox[442] = GameObject.Find("Sphere (442)");
        SphereBox[443] = GameObject.Find("Sphere (443)");
        SphereBox[444] = GameObject.Find("Sphere (444)");
        SphereBox[445] = GameObject.Find("Sphere (445)");
        SphereBox[446] = GameObject.Find("Sphere (446)");
        SphereBox[447] = GameObject.Find("Sphere (447)");
        SphereBox[448] = GameObject.Find("Sphere (448)");
        SphereBox[449] = GameObject.Find("Sphere (449)");
        SphereBox[450] = GameObject.Find("Sphere (450)");
        SphereBox[451] = GameObject.Find("Sphere (451)");
        SphereBox[452] = GameObject.Find("Sphere (452)");
        SphereBox[453] = GameObject.Find("Sphere (453)");
        SphereBox[454] = GameObject.Find("Sphere (454)");
        SphereBox[455] = GameObject.Find("Sphere (455)");
        SphereBox[456] = GameObject.Find("Sphere (456)");
        SphereBox[457] = GameObject.Find("Sphere (457)");
        SphereBox[458] = GameObject.Find("Sphere (458)");
        SphereBox[459] = GameObject.Find("Sphere (459)");
        SphereBox[460] = GameObject.Find("Sphere (460)");
        SphereBox[461] = GameObject.Find("Sphere (461)");
        SphereBox[462] = GameObject.Find("Sphere (462)");
        SphereBox[463] = GameObject.Find("Sphere (463)");
        SphereBox[464] = GameObject.Find("Sphere (464)");
        SphereBox[465] = GameObject.Find("Sphere (465)");
        SphereBox[466] = GameObject.Find("Sphere (466)");
        SphereBox[467] = GameObject.Find("Sphere (467)");
        SphereBox[468] = GameObject.Find("Sphere (468)");
        SphereBox[469] = GameObject.Find("Sphere (469)");
        SphereBox[470] = GameObject.Find("Sphere (470)");
        SphereBox[471] = GameObject.Find("Sphere (471)");
        SphereBox[472] = GameObject.Find("Sphere (472)");
        SphereBox[473] = GameObject.Find("Sphere (473)");
        SphereBox[474] = GameObject.Find("Sphere (474)");
        SphereBox[475] = GameObject.Find("Sphere (475)");
        SphereBox[476] = GameObject.Find("Sphere (476)");
        SphereBox[477] = GameObject.Find("Sphere (477)");
        SphereBox[478] = GameObject.Find("Sphere (478)");
        SphereBox[479] = GameObject.Find("Sphere (479)");
        SphereBox[480] = GameObject.Find("Sphere (480)");
        SphereBox[481] = GameObject.Find("Sphere (481)");
        SphereBox[482] = GameObject.Find("Sphere (482)");
        SphereBox[483] = GameObject.Find("Sphere (483)");
        SphereBox[484] = GameObject.Find("Sphere (484)");
        SphereBox[485] = GameObject.Find("Sphere (485)");
        SphereBox[486] = GameObject.Find("Sphere (486)");
        SphereBox[487] = GameObject.Find("Sphere (487)");
        SphereBox[488] = GameObject.Find("Sphere (488)");
        SphereBox[489] = GameObject.Find("Sphere (489)");
        SphereBox[490] = GameObject.Find("Sphere (490)");
        SphereBox[491] = GameObject.Find("Sphere (491)");
        SphereBox[492] = GameObject.Find("Sphere (492)");
        SphereBox[493] = GameObject.Find("Sphere (493)");
        SphereBox[494] = GameObject.Find("Sphere (494)");
        SphereBox[495] = GameObject.Find("Sphere (495)");
        SphereBox[496] = GameObject.Find("Sphere (496)");
        SphereBox[497] = GameObject.Find("Sphere (497)");
        SphereBox[498] = GameObject.Find("Sphere (498)");
        SphereBox[499] = GameObject.Find("Sphere (499)");
        SphereBox[500] = GameObject.Find("Sphere (500)");
        SphereBox[501] = GameObject.Find("Sphere (501)");
        SphereBox[502] = GameObject.Find("Sphere (502)");
        SphereBox[503] = GameObject.Find("Sphere (503)");
        SphereBox[504] = GameObject.Find("Sphere (504)");
        SphereBox[505] = GameObject.Find("Sphere (505)");
        SphereBox[506] = GameObject.Find("Sphere (506)");
        SphereBox[507] = GameObject.Find("Sphere (507)");
        SphereBox[508] = GameObject.Find("Sphere (508)");
        SphereBox[509] = GameObject.Find("Sphere (509)");
        SphereBox[510] = GameObject.Find("Sphere (510)");
        SphereBox[511] = GameObject.Find("Sphere (511)");
        SphereBox[512] = GameObject.Find("Sphere (512)");
        SphereBox[513] = GameObject.Find("Sphere (513)");
        SphereBox[514] = GameObject.Find("Sphere (514)");
        SphereBox[515] = GameObject.Find("Sphere (515)");
        SphereBox[516] = GameObject.Find("Sphere (516)");
        SphereBox[517] = GameObject.Find("Sphere (517)");
        SphereBox[518] = GameObject.Find("Sphere (518)");
        SphereBox[519] = GameObject.Find("Sphere (519)");
        SphereBox[520] = GameObject.Find("Sphere (520)");
        SphereBox[521] = GameObject.Find("Sphere (521)");
        SphereBox[522] = GameObject.Find("Sphere (522)");
        SphereBox[523] = GameObject.Find("Sphere (523)");
        SphereBox[524] = GameObject.Find("Sphere (524)");
        SphereBox[525] = GameObject.Find("Sphere (525)");
        SphereBox[526] = GameObject.Find("Sphere (526)");
        SphereBox[527] = GameObject.Find("Sphere (527)");
        SphereBox[528] = GameObject.Find("Sphere (528)");
        SphereBox[529] = GameObject.Find("Sphere (529)");
        SphereBox[530] = GameObject.Find("Sphere (530)");
        SphereBox[531] = GameObject.Find("Sphere (531)");
        SphereBox[532] = GameObject.Find("Sphere (532)");
        SphereBox[533] = GameObject.Find("Sphere (533)");
        SphereBox[534] = GameObject.Find("Sphere (534)");
        SphereBox[535] = GameObject.Find("Sphere (535)");
        SphereBox[536] = GameObject.Find("Sphere (536)");
        SphereBox[537] = GameObject.Find("Sphere (537)");
        SphereBox[538] = GameObject.Find("Sphere (538)");
        SphereBox[539] = GameObject.Find("Sphere (539)");
        SphereBox[540] = GameObject.Find("Sphere (540)");
        SphereBox[541] = GameObject.Find("Sphere (541)");
        SphereBox[542] = GameObject.Find("Sphere (542)");
        SphereBox[543] = GameObject.Find("Sphere (543)");
        SphereBox[544] = GameObject.Find("Sphere (544)");
        SphereBox[545] = GameObject.Find("Sphere (545)");
        SphereBox[546] = GameObject.Find("Sphere (546)");
        SphereBox[547] = GameObject.Find("Sphere (547)");
        SphereBox[548] = GameObject.Find("Sphere (548)");
        SphereBox[549] = GameObject.Find("Sphere (549)");
        SphereBox[550] = GameObject.Find("Sphere (550)");
        SphereBox[551] = GameObject.Find("Sphere (551)");
        SphereBox[552] = GameObject.Find("Sphere (552)");
        SphereBox[553] = GameObject.Find("Sphere (553)");
        SphereBox[554] = GameObject.Find("Sphere (554)");
        SphereBox[555] = GameObject.Find("Sphere (555)");
        SphereBox[556] = GameObject.Find("Sphere (556)");
        SphereBox[557] = GameObject.Find("Sphere (557)");
        SphereBox[558] = GameObject.Find("Sphere (558)");
        SphereBox[559] = GameObject.Find("Sphere (559)");
        SphereBox[560] = GameObject.Find("Sphere (560)");
        SphereBox[561] = GameObject.Find("Sphere (561)");
        SphereBox[562] = GameObject.Find("Sphere (562)");
        SphereBox[563] = GameObject.Find("Sphere (563)");
        SphereBox[564] = GameObject.Find("Sphere (564)");
        SphereBox[565] = GameObject.Find("Sphere (565)");
        SphereBox[566] = GameObject.Find("Sphere (566)");
        SphereBox[567] = GameObject.Find("Sphere (567)");
        SphereBox[568] = GameObject.Find("Sphere (568)");
        SphereBox[569] = GameObject.Find("Sphere (569)");
        SphereBox[570] = GameObject.Find("Sphere (570)");
        SphereBox[571] = GameObject.Find("Sphere (571)");
        SphereBox[572] = GameObject.Find("Sphere (572)");
        SphereBox[573] = GameObject.Find("Sphere (573)");
        SphereBox[574] = GameObject.Find("Sphere (574)");
        SphereBox[575] = GameObject.Find("Sphere (575)");
        SphereBox[576] = GameObject.Find("Sphere (576)");
        SphereBox[577] = GameObject.Find("Sphere (577)");
        SphereBox[578] = GameObject.Find("Sphere (578)");
        SphereBox[579] = GameObject.Find("Sphere (579)");
        SphereBox[580] = GameObject.Find("Sphere (580)");
        SphereBox[581] = GameObject.Find("Sphere (581)");
        SphereBox[582] = GameObject.Find("Sphere (582)");
        SphereBox[583] = GameObject.Find("Sphere (583)");
        SphereBox[584] = GameObject.Find("Sphere (584)");
        SphereBox[585] = GameObject.Find("Sphere (585)");
        SphereBox[586] = GameObject.Find("Sphere (586)");
        SphereBox[587] = GameObject.Find("Sphere (587)");
        SphereBox[588] = GameObject.Find("Sphere (588)");
        SphereBox[589] = GameObject.Find("Sphere (589)");
        SphereBox[590] = GameObject.Find("Sphere (590)");
        SphereBox[591] = GameObject.Find("Sphere (591)");
        SphereBox[592] = GameObject.Find("Sphere (592)");
        SphereBox[593] = GameObject.Find("Sphere (593)");
        SphereBox[594] = GameObject.Find("Sphere (594)");
        SphereBox[595] = GameObject.Find("Sphere (595)");
        SphereBox[596] = GameObject.Find("Sphere (596)");
        SphereBox[597] = GameObject.Find("Sphere (597)");
        SphereBox[598] = GameObject.Find("Sphere (598)");
        SphereBox[599] = GameObject.Find("Sphere (599)");
        SphereBox[600] = GameObject.Find("Sphere (600)");
        SphereBox[601] = GameObject.Find("Sphere (601)");
        SphereBox[602] = GameObject.Find("Sphere (602)");
        SphereBox[603] = GameObject.Find("Sphere (603)");
        SphereBox[604] = GameObject.Find("Sphere (604)");
        SphereBox[605] = GameObject.Find("Sphere (605)");
        SphereBox[606] = GameObject.Find("Sphere (606)");
        SphereBox[607] = GameObject.Find("Sphere (607)");
        SphereBox[608] = GameObject.Find("Sphere (608)");
        SphereBox[609] = GameObject.Find("Sphere (609)");
        SphereBox[610] = GameObject.Find("Sphere (610)");
        SphereBox[611] = GameObject.Find("Sphere (611)");
        SphereBox[612] = GameObject.Find("Sphere (612)");
        SphereBox[613] = GameObject.Find("Sphere (613)");
        SphereBox[614] = GameObject.Find("Sphere (614)");
        SphereBox[615] = GameObject.Find("Sphere (615)");
        SphereBox[616] = GameObject.Find("Sphere (616)");
        SphereBox[617] = GameObject.Find("Sphere (617)");
        SphereBox[618] = GameObject.Find("Sphere (618)");
        SphereBox[619] = GameObject.Find("Sphere (619)");
        SphereBox[620] = GameObject.Find("Sphere (620)");
        SphereBox[621] = GameObject.Find("Sphere (621)");
        SphereBox[622] = GameObject.Find("Sphere (622)");
        SphereBox[623] = GameObject.Find("Sphere (623)");
        SphereBox[624] = GameObject.Find("Sphere (624)");
        SphereBox[625] = GameObject.Find("Sphere (625)");
        SphereBox[626] = GameObject.Find("Sphere (626)");
        SphereBox[627] = GameObject.Find("Sphere (627)");
        SphereBox[628] = GameObject.Find("Sphere (628)");
        SphereBox[629] = GameObject.Find("Sphere (629)");
        SphereBox[630] = GameObject.Find("Sphere (630)");
        SphereBox[631] = GameObject.Find("Sphere (631)");
        SphereBox[632] = GameObject.Find("Sphere (632)");
        SphereBox[633] = GameObject.Find("Sphere (633)");
        SphereBox[634] = GameObject.Find("Sphere (634)");
        SphereBox[635] = GameObject.Find("Sphere (635)");
        SphereBox[636] = GameObject.Find("Sphere (636)");
        SphereBox[637] = GameObject.Find("Sphere (637)");
        SphereBox[638] = GameObject.Find("Sphere (638)");
        SphereBox[639] = GameObject.Find("Sphere (639)");
        SphereBox[640] = GameObject.Find("Sphere (640)");
        SphereBox[641] = GameObject.Find("Sphere (641)");
        SphereBox[642] = GameObject.Find("Sphere (642)");
        SphereBox[643] = GameObject.Find("Sphere (643)");
        SphereBox[644] = GameObject.Find("Sphere (644)");
        SphereBox[645] = GameObject.Find("Sphere (645)");
        SphereBox[646] = GameObject.Find("Sphere (646)");
        SphereBox[647] = GameObject.Find("Sphere (647)");
        SphereBox[648] = GameObject.Find("Sphere (648)");
        SphereBox[649] = GameObject.Find("Sphere (649)");
        SphereBox[650] = GameObject.Find("Sphere (650)");
        SphereBox[651] = GameObject.Find("Sphere (651)");
        SphereBox[652] = GameObject.Find("Sphere (652)");
        SphereBox[653] = GameObject.Find("Sphere (653)");
        SphereBox[654] = GameObject.Find("Sphere (654)");
        SphereBox[655] = GameObject.Find("Sphere (655)");
        SphereBox[656] = GameObject.Find("Sphere (656)");
        SphereBox[657] = GameObject.Find("Sphere (657)");
        SphereBox[658] = GameObject.Find("Sphere (658)");
        SphereBox[659] = GameObject.Find("Sphere (659)");
        SphereBox[660] = GameObject.Find("Sphere (660)");
        SphereBox[661] = GameObject.Find("Sphere (661)");
        SphereBox[662] = GameObject.Find("Sphere (662)");
        SphereBox[663] = GameObject.Find("Sphere (663)");
        SphereBox[664] = GameObject.Find("Sphere (664)");
        SphereBox[665] = GameObject.Find("Sphere (665)");
        SphereBox[666] = GameObject.Find("Sphere (666)");
        SphereBox[667] = GameObject.Find("Sphere (667)");
        SphereBox[668] = GameObject.Find("Sphere (668)");
        SphereBox[669] = GameObject.Find("Sphere (669)");
        SphereBox[670] = GameObject.Find("Sphere (670)");
        SphereBox[671] = GameObject.Find("Sphere (671)");
        SphereBox[672] = GameObject.Find("Sphere (672)");
        SphereBox[673] = GameObject.Find("Sphere (673)");
        SphereBox[674] = GameObject.Find("Sphere (674)");
        SphereBox[675] = GameObject.Find("Sphere (675)");
        SphereBox[676] = GameObject.Find("Sphere (676)");
        SphereBox[677] = GameObject.Find("Sphere (677)");
        SphereBox[678] = GameObject.Find("Sphere (678)");
        SphereBox[679] = GameObject.Find("Sphere (679)");
        SphereBox[680] = GameObject.Find("Sphere (680)");
        SphereBox[681] = GameObject.Find("Sphere (681)");
        SphereBox[682] = GameObject.Find("Sphere (682)");
        SphereBox[683] = GameObject.Find("Sphere (683)");
        SphereBox[684] = GameObject.Find("Sphere (684)");
        SphereBox[685] = GameObject.Find("Sphere (685)");
        SphereBox[686] = GameObject.Find("Sphere (686)");
        SphereBox[687] = GameObject.Find("Sphere (687)");
        SphereBox[688] = GameObject.Find("Sphere (688)");
        SphereBox[689] = GameObject.Find("Sphere (689)");
        SphereBox[690] = GameObject.Find("Sphere (690)");
        SphereBox[691] = GameObject.Find("Sphere (691)");
        SphereBox[692] = GameObject.Find("Sphere (692)");
        SphereBox[693] = GameObject.Find("Sphere (693)");
        SphereBox[694] = GameObject.Find("Sphere (694)");
        SphereBox[695] = GameObject.Find("Sphere (695)");
        SphereBox[696] = GameObject.Find("Sphere (696)");
        SphereBox[697] = GameObject.Find("Sphere (697)");
        SphereBox[698] = GameObject.Find("Sphere (698)");
        SphereBox[699] = GameObject.Find("Sphere (699)");
        SphereBox[700] = GameObject.Find("Sphere (700)");
        SphereBox[701] = GameObject.Find("Sphere (701)");
        SphereBox[702] = GameObject.Find("Sphere (702)");
        SphereBox[703] = GameObject.Find("Sphere (703)");
        SphereBox[704] = GameObject.Find("Sphere (704)");
        SphereBox[705] = GameObject.Find("Sphere (705)");
        SphereBox[706] = GameObject.Find("Sphere (706)");
        SphereBox[707] = GameObject.Find("Sphere (707)");
        SphereBox[708] = GameObject.Find("Sphere (708)");
        SphereBox[709] = GameObject.Find("Sphere (709)");
        SphereBox[710] = GameObject.Find("Sphere (710)");
        SphereBox[711] = GameObject.Find("Sphere (711)");
        SphereBox[712] = GameObject.Find("Sphere (712)");
        SphereBox[713] = GameObject.Find("Sphere (713)");
        SphereBox[714] = GameObject.Find("Sphere (714)");
        SphereBox[715] = GameObject.Find("Sphere (715)");
        SphereBox[716] = GameObject.Find("Sphere (716)");
        SphereBox[717] = GameObject.Find("Sphere (717)");
        SphereBox[718] = GameObject.Find("Sphere (718)");
        SphereBox[719] = GameObject.Find("Sphere (719)");
        SphereBox[720] = GameObject.Find("Sphere (720)");
        SphereBox[721] = GameObject.Find("Sphere (721)");
        SphereBox[722] = GameObject.Find("Sphere (722)");
        SphereBox[723] = GameObject.Find("Sphere (723)");
        SphereBox[724] = GameObject.Find("Sphere (724)");
        SphereBox[725] = GameObject.Find("Sphere (725)");
        SphereBox[726] = GameObject.Find("Sphere (726)");
        SphereBox[727] = GameObject.Find("Sphere (727)");
        SphereBox[728] = GameObject.Find("Sphere (728)");
        SphereBox[729] = GameObject.Find("Sphere (729)");
        SphereBox[730] = GameObject.Find("Sphere (730)");
        SphereBox[731] = GameObject.Find("Sphere (731)");
        SphereBox[732] = GameObject.Find("Sphere (732)");
        SphereBox[733] = GameObject.Find("Sphere (733)");
        SphereBox[734] = GameObject.Find("Sphere (734)");
        SphereBox[735] = GameObject.Find("Sphere (735)");
        SphereBox[736] = GameObject.Find("Sphere (736)");
        SphereBox[737] = GameObject.Find("Sphere (737)");
        SphereBox[738] = GameObject.Find("Sphere (738)");
        SphereBox[739] = GameObject.Find("Sphere (739)");
        SphereBox[740] = GameObject.Find("Sphere (740)");
        SphereBox[741] = GameObject.Find("Sphere (741)");
        SphereBox[742] = GameObject.Find("Sphere (742)");
        SphereBox[743] = GameObject.Find("Sphere (743)");
        SphereBox[744] = GameObject.Find("Sphere (744)");
        SphereBox[745] = GameObject.Find("Sphere (745)");
        SphereBox[746] = GameObject.Find("Sphere (746)");
        SphereBox[747] = GameObject.Find("Sphere (747)");
        SphereBox[748] = GameObject.Find("Sphere (748)");
        SphereBox[749] = GameObject.Find("Sphere (749)");
        SphereBox[750] = GameObject.Find("Sphere (750)");
        SphereBox[751] = GameObject.Find("Sphere (751)");
        SphereBox[752] = GameObject.Find("Sphere (752)");
        SphereBox[753] = GameObject.Find("Sphere (753)");
        SphereBox[754] = GameObject.Find("Sphere (754)");
        SphereBox[755] = GameObject.Find("Sphere (755)");
        SphereBox[756] = GameObject.Find("Sphere (756)");
        SphereBox[757] = GameObject.Find("Sphere (757)");
        SphereBox[758] = GameObject.Find("Sphere (758)");
        SphereBox[759] = GameObject.Find("Sphere (759)");
        SphereBox[760] = GameObject.Find("Sphere (760)");
        SphereBox[761] = GameObject.Find("Sphere (761)");
        SphereBox[762] = GameObject.Find("Sphere (762)");
        SphereBox[763] = GameObject.Find("Sphere (763)");
        SphereBox[764] = GameObject.Find("Sphere (764)");
        SphereBox[765] = GameObject.Find("Sphere (765)");
        SphereBox[766] = GameObject.Find("Sphere (766)");
        SphereBox[767] = GameObject.Find("Sphere (767)");
        SphereBox[768] = GameObject.Find("Sphere (768)");
        SphereBox[769] = GameObject.Find("Sphere (769)");
        SphereBox[770] = GameObject.Find("Sphere (770)");
        SphereBox[771] = GameObject.Find("Sphere (771)");
        SphereBox[772] = GameObject.Find("Sphere (772)");
        SphereBox[773] = GameObject.Find("Sphere (773)");
        SphereBox[774] = GameObject.Find("Sphere (774)");
        SphereBox[775] = GameObject.Find("Sphere (775)");
        SphereBox[776] = GameObject.Find("Sphere (776)");
        SphereBox[777] = GameObject.Find("Sphere (777)");
        SphereBox[778] = GameObject.Find("Sphere (778)");
        SphereBox[779] = GameObject.Find("Sphere (779)");
        SphereBox[780] = GameObject.Find("Sphere (780)");
        SphereBox[781] = GameObject.Find("Sphere (781)");
        SphereBox[782] = GameObject.Find("Sphere (782)");
        SphereBox[783] = GameObject.Find("Sphere (783)");
        SphereBox[784] = GameObject.Find("Sphere (784)");
        SphereBox[785] = GameObject.Find("Sphere (785)");
        SphereBox[786] = GameObject.Find("Sphere (786)");
        SphereBox[787] = GameObject.Find("Sphere (787)");
        SphereBox[788] = GameObject.Find("Sphere (788)");
        SphereBox[789] = GameObject.Find("Sphere (789)");
        SphereBox[790] = GameObject.Find("Sphere (790)");
        SphereBox[791] = GameObject.Find("Sphere (791)");
        SphereBox[792] = GameObject.Find("Sphere (792)");
        SphereBox[793] = GameObject.Find("Sphere (793)");
        SphereBox[794] = GameObject.Find("Sphere (794)");
        SphereBox[795] = GameObject.Find("Sphere (795)");
        SphereBox[796] = GameObject.Find("Sphere (796)");
        SphereBox[797] = GameObject.Find("Sphere (797)");
        SphereBox[798] = GameObject.Find("Sphere (798)");
        SphereBox[799] = GameObject.Find("Sphere (799)");



        //Debug.Log(jelly);

    }

    private void Update()
    {
        
        CheckForMouseInput();
        //Debug.Log(jelly.transform.position);
        //pressureForce = (float)System.Math.Abs(jelly.transform.position.x) * 10f;
    }

    private void CheckForMouseInput()
    {
        //if (Input.GetMouseButton(0))
        //{
        //    ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        //    if (Physics.Raycast(ray, out hitInfo))
        //    {
        //        jellyBody = hitInfo.collider.gameObject.GetComponent<JellyBody>();
        //        if (jellyBody != null)
        //        {   Quaternion direction = jelly.transform.rotation;
        //            double x = hitInfo.point.x;
        //            double y = hitInfo.point.y;
        //            double z = hitInfo.point.z;
        //            float t = 180 / (float)System.Math.PI;
        //            jelly.transform.eulerAngles = new Vector3((float)System.Math.Atan(z / y) * t, 0f, -(float)System.Math.Atan(x / y) * t);

        //            inputPoint = hitInfo.point; 
        //            inputPoint += hitInfo.normal * 0.1f;
        //            jellyBody.AddPointForce(pressureForce, inputPoint);

        //    // Material mat = Resources.Load<Material>("Assets/New Material.mat");
        //    //jelly.GetComponent<Renderer>().material = new Material(mat);
        //    //CancelInvoke();
        //    // Invoke("method1", 2.0f);
        //    Debug.Log(hitInfo.point);

        //}
        //    }
        //}


        //ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        //if (Physics.Raycast(ray, out hitInfo))
        //{
        
            if (k<=100)
            {
                for (int i = 0; i <= 799; i++)
                {

                    jellyBody = SphereBox[i].GetComponent<JellyBody>();
                    //    if (jellyBody != null)
                    //    {
                    Quaternion direction = SphereBox[i].transform.rotation;
                    double x = 0.5f;
                    double y = 0.0001f;
                    double z = 0.0001f;
                    float t = 180 / (float)System.Math.PI;
                    SphereBox[i].transform.eulerAngles = new Vector3((float)System.Math.Atan(z / y) * t, 0f, -(float)System.Math.Atan(x / y) * t);

                    inputPoint = new Vector3(0.5f, 0f, 0.0f) + SphereBox[i].transform.position;
                    //inputPoint = new Vector3(0.5f, 0f, 0.0f);
                    inputPoint += new Vector3(0.3f, 0f, 0f);
                    //pressureForce = (((float)System.Math.Abs(SphereBox[i].transform.position.x)) % 3) * 3f;
                    //pressureForce = (((float)System.Math.Abs(SphereBox[i].transform.position.x))*(float)k )/ 100f;
                pressureForce = (((float)System.Math.Abs(SphereBox[i].transform.position.x)) * (float)k) / 100f;
                //pressureForce = ((SphereBox[i].transform.position.x) * (float)k) / 100f;
                //pressureForce = 5f;
                jellyBody.AddPointForce(pressureForce, inputPoint);

                }
            }
            else
            {
            for (int i = 0; i <= 799; i++)
            {

                jellyBody = SphereBox[i].GetComponent<JellyBody>();
                //    if (jellyBody != null)
                //    {
                Quaternion direction = SphereBox[i].transform.rotation;
                double x = 0.5f;
                double y = 0.0001f;
                double z = 0.0001f;
                float t = 180 / (float)System.Math.PI;
                SphereBox[i].transform.eulerAngles = new Vector3((float)System.Math.Atan(z / y) * t, 0f, -(float)System.Math.Atan(x / y) * t);

                inputPoint = new Vector3(0.5f, 0f, 0.0f) + SphereBox[i].transform.position;
                //inputPoint = new Vector3(0.5f, 0f, 0.0f);
                inputPoint += new Vector3(0.3f, 0f, 0f);
                //pressureForce = (((float)System.Math.Abs(SphereBox[i].transform.position.x)) % 2) * 5f;
                pressureForce = ((float)System.Math.Abs(SphereBox[i].transform.position.x)) ;
                //pressureForce = (SphereBox[i].transform.position.x);
                //pressureForce = 5f;
                jellyBody.AddPointForce(pressureForce, inputPoint);

            }
        }
        k += 1f;


            // Material mat = Resources.Load<Material>("Assets/New Material.mat");
            //jelly.GetComponent<Renderer>().material = new Material(mat);
            //CancelInvoke();
            // Invoke("method1", 2.0f);
            
            //    }
             

            //}
        

        //ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        //jellyBody = hitInfo.collider.gameObject.GetComponent<JellyBody>();
        //Quaternion direction = jelly.transform.rotation;
        //double x = 0;
        //double y = 0.5;
        //double z = 0;
        //float t = 180 / (float)System.Math.PI;
        //jelly.transform.eulerAngles = new Vector3((float)System.Math.Atan(z / y) * t, 0f, -(float)System.Math.Atan(x / y) * t);

        //inputPoint = new Vector3(0.0f, 0.5f, 0.0f);
        //inputPoint += new Vector3(0f, 0.1f, 0f);
        //jellyBody.AddPointForce(pressureForce, inputPoint);

    }
    /*private void method1()
     {
         Material mat2 = Resources.Load<Material>("Assets/New Material 4.mat");
         jelly.GetComponent<Renderer>().material = new Material(mat2);


     }*/

}
